
SELECT ANIMAL_TYPE
        ,COUNT(*) COUNT
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY 
        CASE WHEN ANIMAL_TYPE = 'CAT' THEN 1
            WHEN ANIMAL_TYPE = 'DOG' THEN 2
            ELSE 3 END
